
version: 2

models:
  - name: raw_data
    description: "A starter dbt model"
    columns:
      - name: number
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null

  - name: multiple
    description: "A starter dbt model"
    columns:
      - name: number
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
